export const ERR = {
  TENANT_HEADER_MISSING: "TENANT_HEADER_MISSING",
  AUTH_HEADER_MISSING: "AUTH_HEADER_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TENANT_MISSING: "AUTH_TENANT_MISSING",
  AUTH_TENANT_MISMATCH: "AUTH_TENANT_MISMATCH",

  REQUIRED: "REQUIRED",
  INVALID_ENUM: "INVALID_ENUM",
  INVALID_BOOL: "INVALID_BOOL",
  INVALID_ISO_DATETIME: "INVALID_ISO_DATETIME",
  RANGE_INVALID: "RANGE_INVALID",
  OVERLAP: "EFFECTIVE_RANGE_OVERLAP",
  DUPLICATE: "DUPLICATE_KEY",

  CITY_NOT_FOUND: "CITY_NOT_FOUND",
  CITY_INACTIVE: "CITY_INACTIVE",
  CITY_NAME_MISMATCH: "CITY_NAME_MISMATCH",

  FACILITY_NOT_FOUND: "FACILITY_NOT_FOUND",
  FACILITY_INACTIVE: "FACILITY_INACTIVE",

  PIN_NOT_FOUND: "PIN_NOT_FOUND",
  PIN_INACTIVE: "PIN_INACTIVE",

  UPLOAD_INVALID: "UPLOAD_INVALID",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  UPLOAD_NOT_CLEAN: "UPLOAD_NOT_CLEAN",
  // Sprint 13 ΓÇö Exception & NDR
  EXCEPTION_NOT_FOUND: "EXCEPTION_NOT_FOUND",
  EXCEPTION_INVALID_TRANSITION: "EXCEPTION_INVALID_TRANSITION",
  EXCEPTION_EVIDENCE_REQUIRED: "EXCEPTION_EVIDENCE_REQUIRED",
  EXCEPTION_TYPE_INVALID: "EXCEPTION_TYPE_INVALID",
  NDR_REASON_NOT_FOUND: "NDR_REASON_NOT_FOUND",
  NDR_REASON_INACTIVE: "NDR_REASON_INACTIVE",
  NDR_SHIPMENT_NOT_OFD: "NDR_SHIPMENT_NOT_OFD",
  NDR_DUPLICATE_ATTEMPT: "NDR_DUPLICATE_ATTEMPT",
  REATTEMPT_NOT_PENDING: "REATTEMPT_NOT_PENDING",
  // Sprint 12 ΓÇö POD Hardening
  POD_RECEIVER_NAME_REQUIRED: "POD_RECEIVER_NAME_REQUIRED",
  POD_CAPTURED_AT_REQUIRED: "POD_CAPTURED_AT_REQUIRED",
  POD_NOT_FOUND: "POD_NOT_FOUND",
  POD_INCOMPLETE: "POD_INCOMPLETE",
  POD_ALREADY_SEALED: "POD_ALREADY_SEALED",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  // DOC-000088 S6.3/S12 ΓÇö Capability Guard enforcement
  CAPABILITY_NOT_ENABLED: "CAPABILITY_NOT_ENABLED_FOR_TENANT",
  PLAN_ENTITLEMENT_REQUIRED: "PLAN_ENTITLEMENT_REQUIRED",
  ROLE_PERMISSION_DENIED: "ROLE_PERMISSION_DENIED",
  GROWTH_STATE_NOT_MET: "GROWTH_STATE_NOT_MET",
} as const;

export type ErrCode = (typeof ERR)[keyof typeof ERR];

